### ISSUE TITLE
No task runner configurations were found

### ISSUE THREAD

**Issue by Marusyk** [cake-build/cake-vs#90]
I'm using VS 2017 15.6.6 and extension Cake for Visual Studio 0.2.0.0. When build.cake is in the root folder with solution then everything works fine:

\Project\Solution.sln
\Project\build.cake

But I need to move build.cake and other (build.ps1 ...) to cake fodler:
\Project\Solution.sln
\Project\cake\build.cake

Then task runner says: No task runner configurations were found.

I've tried to add .\cake to External Web Tools path but no result. How can I solve that?

**Comment by Marusyk** [comment]
any news?

**Comment by Marusyk** [comment]
closing this issue because the project is dead

**Comment by gep13** [comment]
@Marusyk that is an unfortunate turn of phrase.

This project is not dead, it simply isn't currently a priority.  I am aware that there are some open issues on the extension, and I am hoping to get to them, or perhaps @agc93 will have some time.

I am going to re-open this issue.

**Comment by Marusyk** [comment]
ok, but the last commit was more than year ago. So, it looks like not maintained anymore

**Comment by Marusyk** [comment]
Thanks, I know what is open source and how it works. But each project has owner or community that maintain it, and this community or owner helps people with their issues. I've opened this issue almost a year ago and didn't receive aswer or any help (even that it has low priority now). No response! The  problem for me is not actual anymore. So, I decided to close this issue because, as I said, I didn't receive any response! If no responses and the last commit was more than a year ago then people calls such project as a "dead". How we can know about priorities of the project? Are there any informations or described plans? 

> If you are in a position to help out, feel free to jump in with a Pull Requests

of course, if I will be able to fix that then I prepare PR and not waiting for a year, but I do not know how to develop vs-extension, so it was a reason to open this issue!

**Comment by gep13** [comment]
>@Marusyk said...
I know what is open source and how it works.

So say this, but I am not sure that you do.  I specifically stated that I was going to re-open this issue (so that it can be tracked when there is someone able to look into the problem) and yet you have chosen to close it again.  Why?

You seem to be of the opinion that creating an issue on a repository entitles you to something, but I am going to tell you that it doesn't.  Simply put, there is no guarantee that opening an issue on a repository will get you anything!  In an ideal world, your issue would be addressed and you would get a resolution to your problem, but we don't live in an ideal world.  Time goes by, and perhaps your issue got missed, and you didn't receive a response, but that in itself is not grounds to close the issue, as that doesn't help anyone.

I am going to ask you to not close this issue.  If/when someone comes to look at this repository again, it will be helpful to see what issues are currently open.

> How we can know about priorities of the project? Are there any informations or described plans?

No, I do not believe that these are documented currently.  We have spoken about creating a roadmap for the entire Cake project, but to date, that hasn't yet been created.

**Comment by agc93** [comment]
Just to update this: as it stands today, this is a limitation in Visual Studio, not in the extension.

VS only activates our extension when it locates a `build.cake` file, and the Task Runner component only seems to get activated by the VS Shell. I'll keep looking for ways to work around it, but there's only so much we can do when VS doesn't allow us to change that behaviour...
